import React from 'react'

export default function Paragraph() {
  return (
    <>
    <h6 className='font-bold '>Ensure Happy Childhoods For India’s Children With Child Rights and You NGO</h6>
    <p className='text-muted-foreground'>Started in 1979, CRY - Child Rights and You is a top NGO for children in India. We work for every child&lsquo;s right to a happy, healthy childhood. Our mission is to ensure happier childhoods for every child in India by protecting and upholding their rights. As a leading child rights NGO in India, we are focused on creating lasting change. Together, we can build a future where every child thrives. Help us make a difference today.</p>
    <h6 className='font-bold '>Ensure Happy Childhoods For India’s Children With Child Rights and You NGO</h6>
    <p className='text-muted-foreground'>Started in 1979, CRY - Child Rights and You is a top NGO for children in India. We work for every child&lsquo;s right to a happy, healthy childhood. Our mission is to ensure happier childhoods for every child in India by protecting and upholding their rights. As a leading child rights NGO in India, we are focused on creating lasting change. Together, we can build a future where every child thrives. Help us make a difference today.</p><h6 className='font-bold '>Ensure Happy Childhoods For India’s Children With Child Rights and You NGO</h6>
    <p className='text-muted-foreground'>Started in 1979, CRY - Child Rights and You is a top NGO for children in India. We work for every child&lsquo;s right to a happy, healthy childhood. Our mission is to ensure happier childhoods for every child in India by protecting and upholding their rights. As a leading child rights NGO in India, we are focused on creating lasting change. Together, we can build a future where every child thrives. Help us make a difference today.</p><h6 className='font-bold '>Ensure Happy Childhoods For India’s Children With Child Rights and You NGO</h6>
    <p className='text-muted-foreground'>Started in 1979, CRY - Child Rights and You is a top NGO for children in India. We work for every child&lsquo;s right to a happy, healthy childhood. Our mission is to ensure happier childhoods for every child in India by protecting and upholding their rights. As a leading child rights NGO in India, we are focused on creating lasting change. Together, we can build a future where every child thrives. Help us make a difference today.</p><h6 className='font-bold '>Ensure Happy Childhoods For India’s Children With Child Rights and You NGO</h6>
    <p className='text-muted-foreground'>Started in 1979, CRY - Child Rights and You is a top NGO for children in India. We work for every child&lsquo;s right to a happy, healthy childhood. Our mission is to ensure happier childhoods for every child in India by protecting and upholding their rights. As a leading child rights NGO in India, we are focused on creating lasting change. Together, we can build a future where every child thrives. Help us make a difference today.</p><h6 className='font-bold '>Ensure Happy Childhoods For India’s Children With Child Rights and You NGO</h6>
    <p className='text-muted-foreground'>Started in 1979, CRY - Child Rights and You is a top NGO for children in India. We work for every child&lsquo;s right to a happy, healthy childhood. Our mission is to ensure happier childhoods for every child in India by protecting and upholding their rights. As a leading child rights NGO in India, we are focused on creating lasting change. Together, we can build a future where every child thrives. Help us make a difference today.</p><h6 className='font-bold '>Ensure Happy Childhoods For India’s Children With Child Rights and You NGO</h6>
    <p className='text-muted-foreground'>Started in 1979, CRY - Child Rights and You is a top NGO for children in India. We work for every child&lsquo;s right to a happy, healthy childhood. Our mission is to ensure happier childhoods for every child in India by protecting and upholding their rights. As a leading child rights NGO in India, we are focused on creating lasting change. Together, we can build a future where every child thrives. Help us make a difference today.</p><h6 className='font-bold '>Ensure Happy Childhoods For India’s Children With Child Rights and You NGO</h6>
    <p className='text-muted-foreground'>Started in 1979, CRY - Child Rights and You is a top NGO for children in India. We work for every child&lsquo;s right to a happy, healthy childhood. Our mission is to ensure happier childhoods for every child in India by protecting and upholding their rights. As a leading child rights NGO in India, we are focused on creating lasting change. Together, we can build a future where every child thrives. Help us make a difference today.</p><h6 className='font-bold '>Ensure Happy Childhoods For India’s Children With Child Rights and You NGO</h6>
    <p className='text-muted-foreground'>Started in 1979, CRY - Child Rights and You is a top NGO for children in India. We work for every child&lsquo;s right to a happy, healthy childhood. Our mission is to ensure happier childhoods for every child in India by protecting and upholding their rights. As a leading child rights NGO in India, we are focused on creating lasting change. Together, we can build a future where every child thrives. Help us make a difference today.</p><h6 className='font-bold '>Ensure Happy Childhoods For India’s Children With Child Rights and You NGO</h6>
    <p className='text-muted-foreground'>Started in 1979, CRY - Child Rights and You is a top NGO for children in India. We work for every child&lsquo;s right to a happy, healthy childhood. Our mission is to ensure happier childhoods for every child in India by protecting and upholding their rights. As a leading child rights NGO in India, we are focused on creating lasting change. Together, we can build a future where every child thrives. Help us make a difference today.</p><h6 className='font-bold '>Ensure Happy Childhoods For India’s Children With Child Rights and You NGO</h6>
    <p className='text-muted-foreground'>Started in 1979, CRY - Child Rights and You is a top NGO for children in India. We work for every child&lsquo;s right to a happy, healthy childhood. Our mission is to ensure happier childhoods for every child in India by protecting and upholding their rights. As a leading child rights NGO in India, we are focused on creating lasting change. Together, we can build a future where every child thrives. Help us make a difference today.</p><h6 className='font-bold '>Ensure Happy Childhoods For India’s Children With Child Rights and You NGO</h6>
    <p className='text-muted-foreground'>Started in 1979, CRY - Child Rights and You is a top NGO for children in India. We work for every child&lsquo;s right to a happy, healthy childhood. Our mission is to ensure happier childhoods for every child in India by protecting and upholding their rights. As a leading child rights NGO in India, we are focused on creating lasting change. Together, we can build a future where every child thrives. Help us make a difference today.</p><h6 className='font-bold '>Ensure Happy Childhoods For India’s Children With Child Rights and You NGO</h6>
    <p className='text-muted-foreground'>Started in 1979, CRY - Child Rights and You is a top NGO for children in India. We work for every child&lsquo;s right to a happy, healthy childhood. Our mission is to ensure happier childhoods for every child in India by protecting and upholding their rights. As a leading child rights NGO in India, we are focused on creating lasting change. Together, we can build a future where every child thrives. Help us make a difference today.</p><h6 className='font-bold '>Ensure Happy Childhoods For India’s Children With Child Rights and You NGO</h6>
    <p className='text-muted-foreground'>Started in 1979, CRY - Child Rights and You is a top NGO for children in India. We work for every child&lsquo;s right to a happy, healthy childhood. Our mission is to ensure happier childhoods for every child in India by protecting and upholding their rights. As a leading child rights NGO in India, we are focused on creating lasting change. Together, we can build a future where every child thrives. Help us make a difference today.</p><h6 className='font-bold '>Ensure Happy Childhoods For India’s Children With Child Rights and You NGO</h6>
    <p className='text-muted-foreground'>Started in 1979, CRY - Child Rights and You is a top NGO for children in India. We work for every child&lsquo;s right to a happy, healthy childhood. Our mission is to ensure happier childhoods for every child in India by protecting and upholding their rights. As a leading child rights NGO in India, we are focused on creating lasting change. Together, we can build a future where every child thrives. Help us make a difference today.</p><h6 className='font-bold '>Ensure Happy Childhoods For India’s Children With Child Rights and You NGO</h6>
    <p className='text-muted-foreground'>Started in 1979, CRY - Child Rights and You is a top NGO for children in India. We work for every child&lsquo;s right to a happy, healthy childhood. Our mission is to ensure happier childhoods for every child in India by protecting and upholding their rights. As a leading child rights NGO in India, we are focused on creating lasting change. Together, we can build a future where every child thrives. Help us make a difference today.</p><h6 className='font-bold '>Ensure Happy Childhoods For India’s Children With Child Rights and You NGO</h6>
    <p className='text-muted-foreground'>Started in 1979, CRY - Child Rights and You is a top NGO for children in India. We work for every child&lsquo;s right to a happy, healthy childhood. Our mission is to ensure happier childhoods for every child in India by protecting and upholding their rights. As a leading child rights NGO in India, we are focused on creating lasting change. Together, we can build a future where every child thrives. Help us make a difference today.</p><h6 className='font-bold '>Ensure Happy Childhoods For India’s Children With Child Rights and You NGO</h6>
    <p className='text-muted-foreground'>Started in 1979, CRY - Child Rights and You is a top NGO for children in India. We work for every child&lsquo;s right to a happy, healthy childhood. Our mission is to ensure happier childhoods for every child in India by protecting and upholding their rights. As a leading child rights NGO in India, we are focused on creating lasting change. Together, we can build a future where every child thrives. Help us make a difference today.</p><h6 className='font-bold '>Ensure Happy Childhoods For India’s Children With Child Rights and You NGO</h6>
    <p className='text-muted-foreground'>Started in 1979, CRY - Child Rights and You is a top NGO for children in India. We work for every child&lsquo;s right to a happy, healthy childhood. Our mission is to ensure happier childhoods for every child in India by protecting and upholding their rights. As a leading child rights NGO in India, we are focused on creating lasting change. Together, we can build a future where every child thrives. Help us make a difference today.</p><h6 className='font-bold '>Ensure Happy Childhoods For India’s Children With Child Rights and You NGO</h6>
    <p className='text-muted-foreground'>Started in 1979, CRY - Child Rights and You is a top NGO for children in India. We work for every child&lsquo;s right to a happy, healthy childhood. Our mission is to ensure happier childhoods for every child in India by protecting and upholding their rights. As a leading child rights NGO in India, we are focused on creating lasting change. Together, we can build a future where every child thrives. Help us make a difference today.</p><h6 className='font-bold '>Ensure Happy Childhoods For India’s Children With Child Rights and You NGO</h6>
    <p className='text-muted-foreground'>Started in 1979, CRY - Child Rights and You is a top NGO for children in India. We work for every child&lsquo;s right to a happy, healthy childhood. Our mission is to ensure happier childhoods for every child in India by protecting and upholding their rights. As a leading child rights NGO in India, we are focused on creating lasting change. Together, we can build a future where every child thrives. Help us make a difference today.</p><h6 className='font-bold '>Ensure Happy Childhoods For India’s Children With Child Rights and You NGO</h6>
    <p className='text-muted-foreground'>Started in 1979, CRY - Child Rights and You is a top NGO for children in India. We work for every child&lsquo;s right to a happy, healthy childhood. Our mission is to ensure happier childhoods for every child in India by protecting and upholding their rights. As a leading child rights NGO in India, we are focused on creating lasting change. Together, we can build a future where every child thrives. Help us make a difference today.</p><h6 className='font-bold '>Ensure Happy Childhoods For India’s Children With Child Rights and You NGO</h6>
    <p className='text-muted-foreground'>Started in 1979, CRY - Child Rights and You is a top NGO for children in India. We work for every child&lsquo;s right to a happy, healthy childhood. Our mission is to ensure happier childhoods for every child in India by protecting and upholding their rights. As a leading child rights NGO in India, we are focused on creating lasting change. Together, we can build a future where every child thrives. Help us make a difference today.</p><h6 className='font-bold '>Ensure Happy Childhoods For India’s Children With Child Rights and You NGO</h6>
    <p className='text-muted-foreground'>Started in 1979, CRY - Child Rights and You is a top NGO for children in India. We work for every child&lsquo;s right to a happy, healthy childhood. Our mission is to ensure happier childhoods for every child in India by protecting and upholding their rights. As a leading child rights NGO in India, we are focused on creating lasting change. Together, we can build a future where every child thrives. Help us make a difference today.</p><h6 className='font-bold '>Ensure Happy Childhoods For India’s Children With Child Rights and You NGO</h6>
    <p className='text-muted-foreground'>Started in 1979, CRY - Child Rights and You is a top NGO for children in India. We work for every child&lsquo;s right to a happy, healthy childhood. Our mission is to ensure happier childhoods for every child in India by protecting and upholding their rights. As a leading child rights NGO in India, we are focused on creating lasting change. Together, we can build a future where every child thrives. Help us make a difference today.</p><h6 className='font-bold '>Ensure Happy Childhoods For India’s Children With Child Rights and You NGO</h6>
    <p className='text-muted-foreground'>Started in 1979, CRY - Child Rights and You is a top NGO for children in India. We work for every child&lsquo;s right to a happy, healthy childhood. Our mission is to ensure happier childhoods for every child in India by protecting and upholding their rights. As a leading child rights NGO in India, we are focused on creating lasting change. Together, we can build a future where every child thrives. Help us make a difference today.</p><h6 className='font-bold '>Ensure Happy Childhoods For India’s Children With Child Rights and You NGO</h6>
    <p className='text-muted-foreground'>Started in 1979, CRY - Child Rights and You is a top NGO for children in India. We work for every child&lsquo;s right to a happy, healthy childhood. Our mission is to ensure happier childhoods for every child in India by protecting and upholding their rights. As a leading child rights NGO in India, we are focused on creating lasting change. Together, we can build a future where every child thrives. Help us make a difference today.</p><h6 className='font-bold '>Ensure Happy Childhoods For India’s Children With Child Rights and You NGO</h6>
    <p className='text-muted-foreground'>Started in 1979, CRY - Child Rights and You is a top NGO for children in India. We work for every child&lsquo;s right to a happy, healthy childhood. Our mission is to ensure happier childhoods for every child in India by protecting and upholding their rights. As a leading child rights NGO in India, we are focused on creating lasting change. Together, we can build a future where every child thrives. Help us make a difference today.</p><h6 className='font-bold '>Ensure Happy Childhoods For India’s Children With Child Rights and You NGO</h6>
    <p className='text-muted-foreground'>Started in 1979, CRY - Child Rights and You is a top NGO for children in India. We work for every child&lsquo;s right to a happy, healthy childhood. Our mission is to ensure happier childhoods for every child in India by protecting and upholding their rights. As a leading child rights NGO in India, we are focused on creating lasting change. Together, we can build a future where every child thrives. Help us make a difference today.</p><h6 className='font-bold '>Ensure Happy Childhoods For India’s Children With Child Rights and You NGO</h6>
    <p className='text-muted-foreground'>Started in 1979, CRY - Child Rights and You is a top NGO for children in India. We work for every child&lsquo;s right to a happy, healthy childhood. Our mission is to ensure happier childhoods for every child in India by protecting and upholding their rights. As a leading child rights NGO in India, we are focused on creating lasting change. Together, we can build a future where every child thrives. Help us make a difference today.</p><h6 className='font-bold '>Ensure Happy Childhoods For India’s Children With Child Rights and You NGO</h6>
    <p className='text-muted-foreground'>Started in 1979, CRY - Child Rights and You is a top NGO for children in India. We work for every child&lsquo;s right to a happy, healthy childhood. Our mission is to ensure happier childhoods for every child in India by protecting and upholding their rights. As a leading child rights NGO in India, we are focused on creating lasting change. Together, we can build a future where every child thrives. Help us make a difference today.</p><h6 className='font-bold '>Ensure Happy Childhoods For India’s Children With Child Rights and You NGO</h6>
    <p className='text-muted-foreground'>Started in 1979, CRY - Child Rights and You is a top NGO for children in India. We work for every child&lsquo;s right to a happy, healthy childhood. Our mission is to ensure happier childhoods for every child in India by protecting and upholding their rights. As a leading child rights NGO in India, we are focused on creating lasting change. Together, we can build a future where every child thrives. Help us make a difference today.</p><h6 className='font-bold '>Ensure Happy Childhoods For India’s Children With Child Rights and You NGO</h6>
    <p className='text-muted-foreground'>Started in 1979, CRY - Child Rights and You is a top NGO for children in India. We work for every child&lsquo;s right to a happy, healthy childhood. Our mission is to ensure happier childhoods for every child in India by protecting and upholding their rights. As a leading child rights NGO in India, we are focused on creating lasting change. Together, we can build a future where every child thrives. Help us make a difference today.</p><h6 className='font-bold '>Ensure Happy Childhoods For India’s Children With Child Rights and You NGO</h6>
    <p className='text-muted-foreground'>Started in 1979, CRY - Child Rights and You is a top NGO for children in India. We work for every child&lsquo;s right to a happy, healthy childhood. Our mission is to ensure happier childhoods for every child in India by protecting and upholding their rights. As a leading child rights NGO in India, we are focused on creating lasting change. Together, we can build a future where every child thrives. Help us make a difference today.</p>
    </>
  )
}
